[package]
name = "rexit"
version = "0.1.0"
edition = "2021"
description = "Export your Reddit Chats"
readme = "README.md"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
reqwest = {version = "0.11.16", features = ["blocking"]}
rpassword = "7.2.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.2.1", features = ["derive"] }
