name: Publish

on: 
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: The version to publish in Cargo notation (eg. 1.0.0)


jobs:
  bump:
    name: Bump version
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Bump Version
        run: |
          echo ${{ github.event.inputs.version }}
          sed -i "s/^version = \".*\"$/version = \"${{ github.event.inputs.version }}\"/" Cargo.toml
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout ${{ github.head_ref }}
          git add Cargo.toml
          git commit -m "chore - Release "v${{ github.event.inputs.version }}""
          git push
          git tag "v${{ github.event.inputs.version }}"
          git push --tags

  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, windows, macos]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/test
            asset_name: test-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/test.exe
            asset_name: test-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/test
            asset_name: test-macos          


    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo build --release

    - name: Upload binaries to release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}
