name: Ubuntu-latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: codecov/codecov-action@v3
    - name: Upload coverage reports to Codecov
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
        REXIT_USERNAME: ${{ secrets.REXIT_USERNAME }}
        REXIT_PASSWORD: ${{ secrets.REXIT_PASSWORD }}
      run: cargo test --verbose -- --include-ignored
